#!/bin/bash
# shell script for making libraries required for image processing

libdirs=( ./MobileLighting_Mac/processing/processing/imageLib ./MobileLighting_Mac/processing/processing/pfmLib ./MobileLighting_Mac/calib )

for dir in ${libdirs[@]}
do
    pushd $dir
    make clean
    make
    popd
done

pushd ./MobileLighting_Mac/SerialTools
# swift package update
popd
